name: movbank_mobile
description: "A new Flutter project."
# A linha a seguir impede que o pacote seja publicado acidentalmente em
# pub.dev usando `flutter pub publish`. Isso é preferível para pacotes privados.
publish_to: "none" # Remova esta linha se desejar publicar em pub.dev

# A seção a seguir define a versão e o número da build para sua aplicação.
# A versão é composta por três números separados por pontos, como 1.2.43
# seguido por um número de build opcional, separado por +.
# Tanto a versão quanto o número da build podem ser sobrescritos no flutter
# build especificando --build-name e --build-number, respectivamente.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependências especificam outros pacotes que seu pacote precisa para funcionar.
dependencies:
  flutter:
    sdk: flutter

  # Adiciona a fonte de ícones Cupertino para ícones no estilo iOS.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # O pacote "flutter_lints" contém um conjunto de lints recomendados para
  # encorajar boas práticas de codificação.
  flutter_lints: ^5.0.0

# Para informações sobre a parte genérica do Dart deste arquivo, veja:
# https://dart.dev/tools/pub/pubspec

# A seção a seguir é específica para pacotes Flutter.
flutter:
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
